<?php

namespace NewProjectBundle\Repository;

/**
 * UpuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpuserRepository extends \Doctrine\ORM\EntityRepository


{
    public function findAllOrderByName()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT u FROM NewProjectBundle:Upuser u ORDER BY u.surname ASC');
        return $query->getResult();
    }
}


